package hardware;

public class Settings {

    /**
     * @author Timo and Simon
     */
    //Variables
    public final int ULTRASONIC_GRAB_THRESHOLD;
    public final int ULTRASONIC_UNKNOWN_OBJECT_THRESHOLD;
    public final int ENGINE_FORWARD_SPEED;
    public final int ENGINE_STOP_SPEED_LEFT;
    public final int ENGINE_STOP_SPEED_RIGHT;
    public final int LINE_SENSOR_THRESHOLD;
    public final int LINE_SENSOR_CEILING;
    public final int BLUETOOTH_BAUDRATE;
    public final int GRIPPER_OPEN_FREQUENCY;
    public final int GRIPPER_CLOSE_FREQUENCY;
    public final int ULTRASONIC_INPUT_PIN;
    public final int ULTRASONIC_OUTPUT_PIN;
    public final int LEFT_WHEEL_PIN;
    public final int RIGHT_WHEEL_PIN;
    public final int GRIPPER_PIN;
    public final int IR_RECEIVER_PIN;
    public final int[] LINE_SENSOR_ADC_PINS;

    public Settings(int ULTRASONIC_GRAB_THRESHOLD, int ULTRASONIC_UNKNOWN_OBJECT_THRESHOLD, int ENGINE_FORWARD_SPEED, int ENGINE_STOP_SPEED_LEFT, int ENGINE_STOP_SPEED_RIGHT, int LINE_SENSOR_THRESHOLD, int LINE_SENSOR_CEILING, int BLUETOOTH_BAUDRATE, int GRIPPER_OPEN_FREQUENCY, int GRIPPER_CLOSE_FREQUENCY, int ULTRASONIC_INPUT_PIN, int ULTRASONIC_OUTPUT_PIN, int LEFT_WHEEL_PIN, int RIGHT_WHEEL_PIN, int GRIPPER_PIN, int IR_RECEIVER_PIN, int[] LINE_SENSOR_ADC_PINS) {
        this.ULTRASONIC_GRAB_THRESHOLD = ULTRASONIC_GRAB_THRESHOLD;
        this.ULTRASONIC_UNKNOWN_OBJECT_THRESHOLD = ULTRASONIC_UNKNOWN_OBJECT_THRESHOLD;
        this.ENGINE_FORWARD_SPEED = ENGINE_FORWARD_SPEED;
        this.ENGINE_STOP_SPEED_LEFT = ENGINE_STOP_SPEED_LEFT;
        this.ENGINE_STOP_SPEED_RIGHT = ENGINE_STOP_SPEED_RIGHT;
        this.LINE_SENSOR_THRESHOLD = LINE_SENSOR_THRESHOLD;
        this.LINE_SENSOR_CEILING = LINE_SENSOR_CEILING;
        this.BLUETOOTH_BAUDRATE = BLUETOOTH_BAUDRATE;
        this.GRIPPER_OPEN_FREQUENCY = GRIPPER_OPEN_FREQUENCY;
        this.GRIPPER_CLOSE_FREQUENCY = GRIPPER_CLOSE_FREQUENCY;
        this.ULTRASONIC_INPUT_PIN = ULTRASONIC_INPUT_PIN;
        this.ULTRASONIC_OUTPUT_PIN = ULTRASONIC_OUTPUT_PIN;
        this.LEFT_WHEEL_PIN = LEFT_WHEEL_PIN;
        this.RIGHT_WHEEL_PIN = RIGHT_WHEEL_PIN;
        this.GRIPPER_PIN = GRIPPER_PIN;
        this.IR_RECEIVER_PIN = IR_RECEIVER_PIN;
        this.LINE_SENSOR_ADC_PINS = LINE_SENSOR_ADC_PINS;
    }
}
