package hardware;

public class Settings {

    /**
     * @author Timo and Simon
     */
    //Variables
    public final int ULTRASONIC_THRESHOLD;
    public final int ENGINE_NORMAL_SPEED;
    public final int ENGINE_STOP_SPEED;
    public final int LINE_SENSOR_THRESHOLD;
    public final int LINE_SENSOR_CEILING;
    public final int BLUETOOTH_BAUDRATE;
    public final int GRIPPER_OPEN_FREQUENCY;
    public final int GRIPPER_CLOSE_FREQUENCY;
    public final int ULTRASONIC_INPUT_PIN;
    public final int ULTRASONIC_OUTPUT_PIN;
    public final int LEFT_WHEEL_PIN;
    public final int RIGHT_WHEEL_PIN;
    public final int GRIPPER_PIN;
    public final int IR_RECEIVER_PIN;
    public final int[] LINE_SENSOR_ADC_PINS;

    public Settings(int ULTRASONIC_THRESHOLD, int ENGINE_NORMAL_SPEED, int ENGINE_STOP_SPEED, int LINE_SENSOR_THRESHOLD, int LINE_SENSOR_CEILING, int BLUETOOTH_BAUDRATE, int GRIPPER_OPEN_FREQUENCY, int GRIPPER_CLOSE_FREQUENCY, int ULTRASONIC_INPUT_PIN, int ULTRASONIC_OUTPUT_PIN, int LEFT_WHEEL_PIN, int RIGHT_WHEEL_PIN, int GRIPPER_PIN, int IR_RECEIVER_PIN, int[] LINE_SENSOR_ADC_PINS) {
        this.ULTRASONIC_THRESHOLD = ULTRASONIC_THRESHOLD;
        this.ENGINE_NORMAL_SPEED = ENGINE_NORMAL_SPEED;
        this.ENGINE_STOP_SPEED = ENGINE_STOP_SPEED;
        this.LINE_SENSOR_THRESHOLD = LINE_SENSOR_THRESHOLD;
        this.LINE_SENSOR_CEILING = LINE_SENSOR_CEILING;
        this.BLUETOOTH_BAUDRATE = BLUETOOTH_BAUDRATE;
        this.GRIPPER_OPEN_FREQUENCY = GRIPPER_OPEN_FREQUENCY;
        this.GRIPPER_CLOSE_FREQUENCY = GRIPPER_CLOSE_FREQUENCY;
        this.ULTRASONIC_INPUT_PIN = ULTRASONIC_INPUT_PIN;
        this.ULTRASONIC_OUTPUT_PIN = ULTRASONIC_OUTPUT_PIN;
        this.LEFT_WHEEL_PIN = LEFT_WHEEL_PIN;
        this.RIGHT_WHEEL_PIN = RIGHT_WHEEL_PIN;
        this.GRIPPER_PIN = GRIPPER_PIN;
        this.IR_RECEIVER_PIN = IR_RECEIVER_PIN;
        this.LINE_SENSOR_ADC_PINS = LINE_SENSOR_ADC_PINS;
    }
}
